# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Setting(object):
    def setupUi(self, Setting):
        Setting.setObjectName("Setting")
        Setting.resize(889, 663)
        self.gridLayout = QtWidgets.QGridLayout(Setting)
        self.gridLayout.setObjectName("gridLayout")
        self.SampleGroup = QtWidgets.QGroupBox(Setting)
        self.SampleGroup.setTitle("")
        self.SampleGroup.setObjectName("SampleGroup")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.SampleGroup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.SampleGroup)
        self.label_4.setMinimumSize(QtCore.QSize(150, 30))
        self.label_4.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.SampleGroup)
        self.label.setMinimumSize(QtCore.QSize(60, 35))
        self.label.setMaximumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.Start = QtWidgets.QSpinBox(self.SampleGroup)
        self.Start.setMinimumSize(QtCore.QSize(100, 35))
        self.Start.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Start.setFont(font)
        self.Start.setAlignment(QtCore.Qt.AlignCenter)
        self.Start.setMinimum(-5)
        self.Start.setMaximum(10)
        self.Start.setProperty("value", -5)
        self.Start.setObjectName("Start")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Start)
        self.label_2 = QtWidgets.QLabel(self.SampleGroup)
        self.label_2.setMinimumSize(QtCore.QSize(60, 35))
        self.label_2.setMaximumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.End = QtWidgets.QSpinBox(self.SampleGroup)
        self.End.setMinimumSize(QtCore.QSize(100, 35))
        self.End.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.End.setFont(font)
        self.End.setAlignment(QtCore.Qt.AlignCenter)
        self.End.setMinimum(-5)
        self.End.setMaximum(10)
        self.End.setProperty("value", 6)
        self.End.setObjectName("End")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.End)
        self.label_3 = QtWidgets.QLabel(self.SampleGroup)
        self.label_3.setMinimumSize(QtCore.QSize(60, 35))
        self.label_3.setMaximumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.Step = QtWidgets.QDoubleSpinBox(self.SampleGroup)
        self.Step.setMinimumSize(QtCore.QSize(100, 35))
        self.Step.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Step.setFont(font)
        self.Step.setAlignment(QtCore.Qt.AlignCenter)
        self.Step.setDecimals(3)
        self.Step.setMaximum(1.0)
        self.Step.setSingleStep(0.001)
        self.Step.setProperty("value", 0.001)
        self.Step.setObjectName("Step")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Step)
        self.verticalLayout.addLayout(self.formLayout)
        self.gridLayout.addWidget(self.SampleGroup, 0, 0, 1, 1)
        self.ScreenSizeGroup = QtWidgets.QGroupBox(Setting)
        self.ScreenSizeGroup.setTitle("")
        self.ScreenSizeGroup.setObjectName("ScreenSizeGroup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ScreenSizeGroup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.ScreenSizeGroup)
        self.label_5.setMinimumSize(QtCore.QSize(150, 30))
        self.label_5.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.ScreenSizeGroup)
        self.label_7.setMinimumSize(QtCore.QSize(60, 35))
        self.label_7.setMaximumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.ScreenWidth = QtWidgets.QSpinBox(self.ScreenSizeGroup)
        self.ScreenWidth.setMinimumSize(QtCore.QSize(100, 35))
        self.ScreenWidth.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ScreenWidth.setFont(font)
        self.ScreenWidth.setAlignment(QtCore.Qt.AlignCenter)
        self.ScreenWidth.setMinimum(0)
        self.ScreenWidth.setMaximum(3840)
        self.ScreenWidth.setProperty("value", 1920)
        self.ScreenWidth.setDisplayIntegerBase(10)
        self.ScreenWidth.setObjectName("ScreenWidth")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ScreenWidth)
        self.label_8 = QtWidgets.QLabel(self.ScreenSizeGroup)
        self.label_8.setMinimumSize(QtCore.QSize(60, 35))
        self.label_8.setMaximumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.ScreenHeight = QtWidgets.QSpinBox(self.ScreenSizeGroup)
        self.ScreenHeight.setMinimumSize(QtCore.QSize(100, 35))
        self.ScreenHeight.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ScreenHeight.setFont(font)
        self.ScreenHeight.setAlignment(QtCore.Qt.AlignCenter)
        self.ScreenHeight.setMinimum(0)
        self.ScreenHeight.setMaximum(3840)
        self.ScreenHeight.setProperty("value", 1080)
        self.ScreenHeight.setObjectName("ScreenHeight")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ScreenHeight)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.gridLayout.addWidget(self.ScreenSizeGroup, 0, 1, 1, 2)
        self.UdpGroup = QtWidgets.QGroupBox(Setting)
        self.UdpGroup.setTitle("")
        self.UdpGroup.setObjectName("UdpGroup")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.UdpGroup)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.UdpGroup)
        self.label_6.setMinimumSize(QtCore.QSize(150, 30))
        self.label_6.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_10 = QtWidgets.QLabel(self.UdpGroup)
        self.label_10.setMinimumSize(QtCore.QSize(60, 35))
        self.label_10.setMaximumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.UdpIP = QtWidgets.QLineEdit(self.UdpGroup)
        self.UdpIP.setMinimumSize(QtCore.QSize(200, 35))
        self.UdpIP.setMaximumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.UdpIP.setFont(font)
        self.UdpIP.setText("")
        self.UdpIP.setObjectName("UdpIP")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.UdpIP)
        self.label_9 = QtWidgets.QLabel(self.UdpGroup)
        self.label_9.setMinimumSize(QtCore.QSize(60, 35))
        self.label_9.setMaximumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.UdpPort = QtWidgets.QSpinBox(self.UdpGroup)
        self.UdpPort.setMinimumSize(QtCore.QSize(120, 35))
        self.UdpPort.setMaximumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.UdpPort.setFont(font)
        self.UdpPort.setAlignment(QtCore.Qt.AlignCenter)
        self.UdpPort.setMinimum(100)
        self.UdpPort.setMaximum(60000)
        self.UdpPort.setProperty("value", 12301)
        self.UdpPort.setObjectName("UdpPort")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.UdpPort)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.gridLayout.addWidget(self.UdpGroup, 0, 3, 1, 1)
        self.AxisGroup = QtWidgets.QGroupBox(Setting)
        self.AxisGroup.setTitle("")
        self.AxisGroup.setObjectName("AxisGroup")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.AxisGroup)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.AxisGroup)
        self.label_11.setMinimumSize(QtCore.QSize(170, 30))
        self.label_11.setMaximumSize(QtCore.QSize(170, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_12 = QtWidgets.QLabel(self.AxisGroup)
        self.label_12.setMinimumSize(QtCore.QSize(90, 35))
        self.label_12.setMaximumSize(QtCore.QSize(90, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.TickSize = QtWidgets.QSpinBox(self.AxisGroup)
        self.TickSize.setMinimumSize(QtCore.QSize(100, 35))
        self.TickSize.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.TickSize.setFont(font)
        self.TickSize.setAlignment(QtCore.Qt.AlignCenter)
        self.TickSize.setMinimum(5)
        self.TickSize.setMaximum(100)
        self.TickSize.setProperty("value", 40)
        self.TickSize.setDisplayIntegerBase(10)
        self.TickSize.setObjectName("TickSize")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.TickSize)
        self.label_13 = QtWidgets.QLabel(self.AxisGroup)
        self.label_13.setMinimumSize(QtCore.QSize(100, 35))
        self.label_13.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.XleftWidth = QtWidgets.QSpinBox(self.AxisGroup)
        self.XleftWidth.setMinimumSize(QtCore.QSize(100, 35))
        self.XleftWidth.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.XleftWidth.setFont(font)
        self.XleftWidth.setAlignment(QtCore.Qt.AlignCenter)
        self.XleftWidth.setMinimum(10)
        self.XleftWidth.setMaximum(200)
        self.XleftWidth.setSingleStep(1)
        self.XleftWidth.setProperty("value", 100)
        self.XleftWidth.setObjectName("XleftWidth")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.XleftWidth)
        self.label_14 = QtWidgets.QLabel(self.AxisGroup)
        self.label_14.setMinimumSize(QtCore.QSize(130, 35))
        self.label_14.setMaximumSize(QtCore.QSize(130, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.BottomHeight = QtWidgets.QSpinBox(self.AxisGroup)
        self.BottomHeight.setMinimumSize(QtCore.QSize(100, 35))
        self.BottomHeight.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.BottomHeight.setFont(font)
        self.BottomHeight.setAlignment(QtCore.Qt.AlignCenter)
        self.BottomHeight.setMinimum(10)
        self.BottomHeight.setMaximum(200)
        self.BottomHeight.setSingleStep(1)
        self.BottomHeight.setProperty("value", 40)
        self.BottomHeight.setObjectName("BottomHeight")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.BottomHeight)
        self.verticalLayout_5.addLayout(self.formLayout_5)
        self.gridLayout.addWidget(self.AxisGroup, 1, 0, 1, 2)
        self.PlotGroup = QtWidgets.QGroupBox(Setting)
        self.PlotGroup.setTitle("")
        self.PlotGroup.setObjectName("PlotGroup")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.PlotGroup)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_15 = QtWidgets.QLabel(self.PlotGroup)
        self.label_15.setMinimumSize(QtCore.QSize(170, 30))
        self.label_15.setMaximumSize(QtCore.QSize(170, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_17 = QtWidgets.QLabel(self.PlotGroup)
        self.label_17.setMinimumSize(QtCore.QSize(100, 35))
        self.label_17.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.TitleSize = QtWidgets.QSpinBox(self.PlotGroup)
        self.TitleSize.setMinimumSize(QtCore.QSize(100, 35))
        self.TitleSize.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.TitleSize.setFont(font)
        self.TitleSize.setAlignment(QtCore.Qt.AlignCenter)
        self.TitleSize.setMinimum(5)
        self.TitleSize.setMaximum(100)
        self.TitleSize.setProperty("value", 40)
        self.TitleSize.setDisplayIntegerBase(10)
        self.TitleSize.setObjectName("TitleSize")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.TitleSize)
        self.label_18 = QtWidgets.QLabel(self.PlotGroup)
        self.label_18.setMinimumSize(QtCore.QSize(120, 35))
        self.label_18.setMaximumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.LegendSize = QtWidgets.QSpinBox(self.PlotGroup)
        self.LegendSize.setMinimumSize(QtCore.QSize(100, 35))
        self.LegendSize.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LegendSize.setFont(font)
        self.LegendSize.setAlignment(QtCore.Qt.AlignCenter)
        self.LegendSize.setMinimum(1)
        self.LegendSize.setMaximum(50)
        self.LegendSize.setSingleStep(1)
        self.LegendSize.setProperty("value", 10)
        self.LegendSize.setObjectName("LegendSize")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LegendSize)
        self.label_16 = QtWidgets.QLabel(self.PlotGroup)
        self.label_16.setMinimumSize(QtCore.QSize(100, 35))
        self.label_16.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.LineWidth = QtWidgets.QSpinBox(self.PlotGroup)
        self.LineWidth.setMinimumSize(QtCore.QSize(100, 35))
        self.LineWidth.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LineWidth.setFont(font)
        self.LineWidth.setAlignment(QtCore.Qt.AlignCenter)
        self.LineWidth.setMinimum(1)
        self.LineWidth.setMaximum(100)
        self.LineWidth.setSingleStep(1)
        self.LineWidth.setProperty("value", 10)
        self.LineWidth.setObjectName("LineWidth")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineWidth)
        self.label_19 = QtWidgets.QLabel(self.PlotGroup)
        self.label_19.setMinimumSize(QtCore.QSize(120, 35))
        self.label_19.setMaximumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_25 = QtWidgets.QLabel(self.PlotGroup)
        self.label_25.setMinimumSize(QtCore.QSize(120, 35))
        self.label_25.setMaximumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.LineColor1 = QtWidgets.QPushButton(self.PlotGroup)
        self.LineColor1.setMinimumSize(QtCore.QSize(100, 35))
        self.LineColor1.setMaximumSize(QtCore.QSize(100, 35))
        self.LineColor1.setObjectName("LineColor1")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineColor1)
        self.LineColor2 = QtWidgets.QPushButton(self.PlotGroup)
        self.LineColor2.setMinimumSize(QtCore.QSize(100, 35))
        self.LineColor2.setMaximumSize(QtCore.QSize(100, 35))
        self.LineColor2.setObjectName("LineColor2")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineColor2)
        self.verticalLayout_4.addLayout(self.formLayout_4)
        self.gridLayout.addWidget(self.PlotGroup, 1, 2, 1, 2)

        self.retranslateUi(Setting)
        QtCore.QMetaObject.connectSlotsByName(Setting)

    def retranslateUi(self, Setting):
        _translate = QtCore.QCoreApplication.translate
        Setting.setWindowTitle(_translate("Setting", "Setting"))
        self.label_4.setText(_translate("Setting", "SampleRate:"))
        self.label.setText(_translate("Setting", "Start:"))
        self.label_2.setText(_translate("Setting", "End:"))
        self.label_3.setText(_translate("Setting", "Step:"))
        self.label_5.setText(_translate("Setting", "ScreenSize:"))
        self.label_7.setText(_translate("Setting", "Width:"))
        self.label_8.setText(_translate("Setting", "Height:"))
        self.label_6.setText(_translate("Setting", "UdpSetting:"))
        self.label_10.setText(_translate("Setting", "IP:"))
        self.label_9.setText(_translate("Setting", "Port:"))
        self.label_11.setText(_translate("Setting", "AxisSetting:"))
        self.label_12.setText(_translate("Setting", "TickSize:"))
        self.label_13.setText(_translate("Setting", "LeftWidth:"))
        self.label_14.setText(_translate("Setting", "BottomHeight:"))
        self.label_15.setText(_translate("Setting", "PlotSetting:"))
        self.label_17.setText(_translate("Setting", "TitleSize:"))
        self.label_18.setText(_translate("Setting", "LegendSize:"))
        self.label_16.setText(_translate("Setting", "LineWidth:"))
        self.label_19.setText(_translate("Setting", "LineColor1:"))
        self.label_25.setText(_translate("Setting", "LineColor2:"))
        self.LineColor1.setText(_translate("Setting", "Color"))
        self.LineColor2.setText(_translate("Setting", "Color"))
