# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Setting(object):
    def setupUi(self, Setting):
        Setting.setObjectName("Setting")
        Setting.resize(889, 663)
        self.gridLayout_2 = QtWidgets.QGridLayout(Setting)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line = QtWidgets.QFrame(Setting)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(Setting)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 0, 1, 1, 1)
        self.SampleGroup = QtWidgets.QGroupBox(Setting)
        self.SampleGroup.setTitle("")
        self.SampleGroup.setObjectName("SampleGroup")
        self.widget = QtWidgets.QWidget(self.SampleGroup)
        self.widget.setGeometry(QtCore.QRect(30, 30, 522, 352))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setMinimumSize(QtCore.QSize(130, 35))
        self.label_14.setMaximumSize(QtCore.QSize(130, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setMinimumSize(QtCore.QSize(60, 30))
        self.label_11.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setMinimumSize(QtCore.QSize(120, 35))
        self.label_18.setMaximumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 6, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(60, 0))
        self.label_2.setMaximumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.widget)
        self.label_25.setMinimumSize(QtCore.QSize(120, 35))
        self.label_25.setMaximumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 8, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setMinimumSize(QtCore.QSize(60, 35))
        self.label_7.setMaximumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setMinimumSize(QtCore.QSize(120, 30))
        self.label_5.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.BottomHeight = QtWidgets.QSpinBox(self.widget)
        self.BottomHeight.setMinimumSize(QtCore.QSize(100, 25))
        self.BottomHeight.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BottomHeight.setFont(font)
        self.BottomHeight.setAlignment(QtCore.Qt.AlignCenter)
        self.BottomHeight.setMinimum(10)
        self.BottomHeight.setMaximum(200)
        self.BottomHeight.setSingleStep(1)
        self.BottomHeight.setProperty("value", 40)
        self.BottomHeight.setObjectName("BottomHeight")
        self.gridLayout.addWidget(self.BottomHeight, 3, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setMinimumSize(QtCore.QSize(65, 35))
        self.label_8.setMaximumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 3, 1, 1)
        self.LegendSize = QtWidgets.QSpinBox(self.widget)
        self.LegendSize.setMinimumSize(QtCore.QSize(100, 25))
        self.LegendSize.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.LegendSize.setFont(font)
        self.LegendSize.setAlignment(QtCore.Qt.AlignCenter)
        self.LegendSize.setMinimum(1)
        self.LegendSize.setMaximum(50)
        self.LegendSize.setSingleStep(1)
        self.LegendSize.setProperty("value", 10)
        self.LegendSize.setObjectName("LegendSize")
        self.gridLayout.addWidget(self.LegendSize, 7, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setMinimumSize(QtCore.QSize(120, 35))
        self.label_19.setMaximumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 8, 1, 1, 1)
        self.XleftWidth = QtWidgets.QSpinBox(self.widget)
        self.XleftWidth.setMinimumSize(QtCore.QSize(100, 25))
        self.XleftWidth.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.XleftWidth.setFont(font)
        self.XleftWidth.setAlignment(QtCore.Qt.AlignCenter)
        self.XleftWidth.setMinimum(10)
        self.XleftWidth.setMaximum(200)
        self.XleftWidth.setSingleStep(1)
        self.XleftWidth.setProperty("value", 100)
        self.XleftWidth.setObjectName("XleftWidth")
        self.gridLayout.addWidget(self.XleftWidth, 3, 3, 1, 1)
        self.Start = QtWidgets.QSpinBox(self.widget)
        self.Start.setMinimumSize(QtCore.QSize(100, 25))
        self.Start.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Start.setFont(font)
        self.Start.setAlignment(QtCore.Qt.AlignCenter)
        self.Start.setMinimum(-5)
        self.Start.setMaximum(10)
        self.Start.setProperty("value", -5)
        self.Start.setObjectName("Start")
        self.gridLayout.addWidget(self.Start, 1, 1, 1, 1)
        self.TitleSize = QtWidgets.QSpinBox(self.widget)
        self.TitleSize.setMinimumSize(QtCore.QSize(100, 25))
        self.TitleSize.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TitleSize.setFont(font)
        self.TitleSize.setAlignment(QtCore.Qt.AlignCenter)
        self.TitleSize.setMinimum(5)
        self.TitleSize.setMaximum(100)
        self.TitleSize.setProperty("value", 40)
        self.TitleSize.setDisplayIntegerBase(10)
        self.TitleSize.setObjectName("TitleSize")
        self.gridLayout.addWidget(self.TitleSize, 7, 1, 1, 1)
        self.ScreenHeight = QtWidgets.QSpinBox(self.widget)
        self.ScreenHeight.setMinimumSize(QtCore.QSize(100, 25))
        self.ScreenHeight.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ScreenHeight.setFont(font)
        self.ScreenHeight.setAlignment(QtCore.Qt.AlignCenter)
        self.ScreenHeight.setMinimum(0)
        self.ScreenHeight.setMaximum(3840)
        self.ScreenHeight.setProperty("value", 1080)
        self.ScreenHeight.setObjectName("ScreenHeight")
        self.gridLayout.addWidget(self.ScreenHeight, 5, 3, 1, 1)
        self.LineWidth = QtWidgets.QSpinBox(self.widget)
        self.LineWidth.setMinimumSize(QtCore.QSize(100, 25))
        self.LineWidth.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.LineWidth.setFont(font)
        self.LineWidth.setAlignment(QtCore.Qt.AlignCenter)
        self.LineWidth.setMinimum(1)
        self.LineWidth.setMaximum(100)
        self.LineWidth.setSingleStep(1)
        self.LineWidth.setProperty("value", 10)
        self.LineWidth.setObjectName("LineWidth")
        self.gridLayout.addWidget(self.LineWidth, 7, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setMinimumSize(QtCore.QSize(90, 35))
        self.label_12.setMaximumSize(QtCore.QSize(90, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 1, 1, 1)
        self.LineColor2 = QtWidgets.QPushButton(self.widget)
        self.LineColor2.setMinimumSize(QtCore.QSize(100, 25))
        self.LineColor2.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LineColor2.setFont(font)
        self.LineColor2.setObjectName("LineColor2")
        self.gridLayout.addWidget(self.LineColor2, 9, 3, 1, 1)
        self.TickSize = QtWidgets.QSpinBox(self.widget)
        self.TickSize.setMinimumSize(QtCore.QSize(100, 25))
        self.TickSize.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TickSize.setFont(font)
        self.TickSize.setAlignment(QtCore.Qt.AlignCenter)
        self.TickSize.setMinimum(5)
        self.TickSize.setMaximum(100)
        self.TickSize.setProperty("value", 40)
        self.TickSize.setDisplayIntegerBase(10)
        self.TickSize.setObjectName("TickSize")
        self.gridLayout.addWidget(self.TickSize, 3, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(60, 30))
        self.label_15.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 7, 0, 1, 1)
        self.Step = QtWidgets.QDoubleSpinBox(self.widget)
        self.Step.setMinimumSize(QtCore.QSize(100, 25))
        self.Step.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Step.setFont(font)
        self.Step.setAlignment(QtCore.Qt.AlignCenter)
        self.Step.setDecimals(6)
        self.Step.setMaximum(1.0)
        self.Step.setMinimum(0.000001)
        self.Step.setSingleStep(.000001)
        self.Step.setProperty("value", 0.001)
        self.Step.setObjectName("Step")
        self.gridLayout.addWidget(self.Step, 1, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(60, 0))
        self.label.setMaximumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.ScreenWidth = QtWidgets.QSpinBox(self.widget)
        self.ScreenWidth.setMinimumSize(QtCore.QSize(100, 25))
        self.ScreenWidth.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ScreenWidth.setFont(font)
        self.ScreenWidth.setAlignment(QtCore.Qt.AlignCenter)
        self.ScreenWidth.setMinimum(0)
        self.ScreenWidth.setMaximum(3840)
        self.ScreenWidth.setProperty("value", 1920)
        self.ScreenWidth.setDisplayIntegerBase(10)
        self.ScreenWidth.setObjectName("ScreenWidth")
        self.gridLayout.addWidget(self.ScreenWidth, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMinimumSize(QtCore.QSize(60, 0))
        self.label_3.setMaximumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setMinimumSize(QtCore.QSize(100, 35))
        self.label_13.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setMinimumSize(QtCore.QSize(70, 30))
        self.label_4.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.LineColor1 = QtWidgets.QPushButton(self.widget)
        self.LineColor1.setMinimumSize(QtCore.QSize(100, 25))
        self.LineColor1.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LineColor1.setFont(font)
        self.LineColor1.setObjectName("LineColor1")
        self.gridLayout.addWidget(self.LineColor1, 9, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setMinimumSize(QtCore.QSize(100, 35))
        self.label_17.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 6, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setMinimumSize(QtCore.QSize(100, 35))
        self.label_16.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 6, 5, 1, 1)
        self.End = QtWidgets.QSpinBox(self.widget)
        self.End.setMinimumSize(QtCore.QSize(100, 25))
        self.End.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.End.setFont(font)
        self.End.setAlignment(QtCore.Qt.AlignCenter)
        self.End.setMinimum(-5)
        self.End.setMaximum(10)
        self.End.setProperty("value", 6)
        self.End.setObjectName("End")
        self.gridLayout.addWidget(self.End, 1, 3, 1, 1)
        self.gridLayout_2.addWidget(self.SampleGroup, 1, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(Setting)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 1, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(Setting)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 1, 2, 1, 1)

        self.retranslateUi(Setting)
        QtCore.QMetaObject.connectSlotsByName(Setting)

    def retranslateUi(self, Setting):
        _translate = QtCore.QCoreApplication.translate
        Setting.setWindowTitle(_translate("Setting", "Graph Cfg"))
        self.label_14.setText(_translate("Setting", "BottomHeight:"))
        self.label_11.setText(_translate("Setting", "Axis:"))
        self.label_18.setText(_translate("Setting", "LegendSize:"))
        self.label_2.setText(_translate("Setting", "End:"))
        self.label_25.setText(_translate("Setting", "LineColor2:"))
        self.label_7.setText(_translate("Setting", "Width:"))
        self.label_5.setText(_translate("Setting", "ScreenSize:"))
        self.label_8.setText(_translate("Setting", "Height:"))
        self.label_19.setText(_translate("Setting", "LineColor1:"))
        self.label_12.setText(_translate("Setting", "TickSize:"))
        self.LineColor2.setText(_translate("Setting", "Color"))
        self.label_15.setText(_translate("Setting", "Plot:"))
        self.label.setText(_translate("Setting", "Start:"))
        self.label_3.setText(_translate("Setting", "Step:"))
        self.label_13.setText(_translate("Setting", "LeftWidth:"))
        self.label_4.setText(_translate("Setting", "Sample:"))
        self.LineColor1.setText(_translate("Setting", "Color"))
        self.label_17.setText(_translate("Setting", "TitleSize:"))
        self.label_16.setText(_translate("Setting", "LineWidth:"))
